package com.example.novelonline.fragments

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.LinearLayout
import android.widget.TextView
import androidx.fragment.app.Fragment
import androidx.navigation.fragment.findNavController
import com.example.novelonline.R
import com.example.novelonline.databinding.FragmentBecomeAWriterBinding //generated by View Binding

class BecomeWriterFragment : Fragment() {

    // Declare a binding object
    private var _binding: FragmentBecomeAWriterBinding? = null
    // This property is only valid between onCreateView and onDestroyView.
    private val binding get() = _binding!!

    // Declare views
    private lateinit var backArrow: TextView
    private lateinit var createNewBookCard: LinearLayout
    private lateinit var goWriteChaptersCard: LinearLayout

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout using View Binding
        _binding = FragmentBecomeAWriterBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        // Initialize views using the binding object
        backArrow = binding.backArrow
        createNewBookCard = binding.createNewBookCard
        goWriteChaptersCard = binding.goWriteChaptersCard

        // Set click listener for the back arrow
        backArrow.setOnClickListener {
            findNavController().navigateUp()
        }

        createNewBookCard.setOnClickListener {
            findNavController().navigate(R.id.action_becomeWriterFragment_to_addTitleFragment)
        }
        goWriteChaptersCard.setOnClickListener {
            findNavController().navigate(R.id.action_becomeWriterFragment_to_UploadPdfFragment)
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        // Clear the binding object to avoid memory leaks
        _binding = null
    }

    companion object {
        fun newInstance() = BecomeWriterFragment()
    }
}